import { __platform_browser_private__ as _ } from '@angular/platform-browser';
export declare type DomAdapter = typeof _.DomAdapter;
export declare var DomAdapter: typeof _.DomAdapter;
export declare var setRootDomAdapter: typeof _.setRootDomAdapter;
export declare var getDOM: typeof _.getDOM;
export declare type DomRootRenderer = typeof _.DomRootRenderer;
export declare var DomRootRenderer: typeof _.DomRootRenderer;
export declare type DomRootRenderer_ = typeof _.DomRootRenderer_;
export declare var DomRootRenderer_: typeof _.DomRootRenderer_;
export declare type DomSharedStylesHost = typeof _.DomSharedStylesHost;
export declare var DomSharedStylesHost: typeof _.DomSharedStylesHost;
export declare type SharedStylesHost = typeof _.SharedStylesHost;
export declare var SharedStylesHost: typeof _.SharedStylesHost;
